# Build stage
FROM node:20 AS build

WORKDIR /app

COPY common-ground/package*.json ./
RUN npm install

COPY common-ground/ .

RUN npm run build


# Production stage
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY common-ground/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80